import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
       System.out.println("Java 1.5 - Autoboxing example :"+ new App().autoBoxingExample(20));
       System.out.println("Java 1.5 - Unboxing example :"+ new App().unBoxingExample(30));
       ForEachLoop.runForEachLoopSamples();
       StaticImport.staticImportUsage();
       vararg.varargexample(1,2,3,4);
    }
    public Integer autoBoxingExample(int integerValue){
        System.out.println("This autoboxing");
        int prmtivetypeInt = integerValue;
        Integer wrapperInt=prmtivetypeInt;
        System.out.println("Premitive automatically converted to Wrapper type (Compiler does this automatically Integer.valueOf(prmtivetypeInt)): "+wrapperInt);
        return wrapperInt;
    }
    public int unBoxingExample(Integer wrapperValue){
        System.out.println("This unboxing");
        Integer wrapperInt=wrapperValue;
        int prmInt=wrapperInt;
        System.out.println("Wapper type automatically converted to Premitive type (// Compiler does this automatically wrapperInt.intValue()): "+ prmInt);
        return prmInt;
    }
}
