/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AutoboxingUnboxing {

    public static void main(String[] args) {
       new AutoboxingUnboxing().autoBoxingExample();
       new AutoboxingUnboxing().unBoxingExample();

    }
    public void autoBoxingExample(){
        System.out.println("This autoboxing");
        int prmtivetypeInt = 20;
        Integer wrapperInt=prmtivetypeInt;
        System.out.println("Premitive automatically converted to Wrapper type (Compiler does this automatically Integer.valueOf(prmtivetypeInt)): "+wrapperInt);

    }
    public void unBoxingExample(){
        System.out.println("This unboxing");
        Integer wrapperInt=30;
        int prmInt=wrapperInt;
        System.out.println("Wapper type automatically converted to Premitive type (// Compiler does this automatically wrapperInt.intValue()): "+ prmInt);
    }
}
