/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AutoboxingUnboxing {

    public static void main(String[] args) {
       System.out.println("Java 1.5 - Autoboxing example :"+ new AutoboxingUnboxing().autoBoxingExample());
       System.out.println("Java 1.5 - Unboxing example :"+ new AutoboxingUnboxing().unBoxingExample());

    }
    public Integer autoBoxingExample(){
        System.out.println("This autoboxing");
        int prmtivetypeInt = 20;
        Integer wrapperInt=prmtivetypeInt;
        System.out.println("Premitive automatically converted to Wrapper type (Compiler does this automatically Integer.valueOf(prmtivetypeInt)): "+wrapperInt);
        return wrapperInt;
    }
    public int unBoxingExample(){
        System.out.println("This unboxing");
        Integer wrapperInt=30;
        int prmInt=wrapperInt;
        System.out.println("Wapper type automatically converted to Premitive type (// Compiler does this automatically wrapperInt.intValue()): "+ prmInt);
        return prmInt;
    }
}
