/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAutoBoxing() {
        App classUnderTest = new App();
        int primitiveType =20;
        assertTrue(classUnderTest.autoBoxingExample(primitiveType) instanceof Integer);
    }
    @Test
    public void testUnBoxing(){
        App classUnderTest = new App();
        Integer wrapperType = new Integer (30);
        assertTrue(30 == classUnderTest.unBoxingExample(wrapperType));
    }
}
